version: "3.9"
services:


  alysonq:
    image: gennyproject/alyson:latest
    container_name: alysonq
    depends_on:
      - bridgeq
    ports:
      - "7000:8080"
    environment:
      - VIRTUAL_HOST=internmatch.*,mentormatch.*,capstonematch.*,stt.genny.life,alyson.*
      - VIRTUAL_PORT=8080
      - NODE_ENV=production
    networks:
      - mainproxy
    restart: always

volumes:
  mysql_data:
  minio_conf:
  minio_data:
  maildata:
    driver: local
  mailstate:
    driver: local
networks:
  mainproxy:
    driver: bridge
