version: "3.9"
services:

  #messagesq:
    #image: gennyproject/messagesq:latest
    #container_name: messagesq 
    #environment:
      #- FULL_MYSQL_URL=mysqlq:3306/gennydb?zeroDateTimeBehavior=convertToNull
    #ports:
      #- 8380:8080
    #networks:
      #- mainproxy
    #depends_on:
      #- mysqlq
    #deploy:
      #replicas: 1
      #labels: [APP=JAR]
      #update_config:
        #parallelism: 2
        #delay: 10s
      #restart_policy:
        #condition: on-failure
        #delay: 10s
        #max_attempts: 3
        #window: 120s

  imageproxyq:
    image: willnorris/imageproxy:v0.10.0
    container_name: imageproxyq
    ports:
      - "46243:8080"
    networks:
      - mainproxy
    command: -cache /tmp/imageproxy -addr 0.0.0.0:8080 -scaleUp true

  apiq:
    image: gennyproject/apiq:latest
    environment:
      - FULL_MYSQL_URL=mysqlq:3306/gennydb?zeroDateTimeBehavior=convertToNull
    networks:
      - mainproxy
    depends_on:
      - mysqlq
    deploy:
      replicas: 2 
      labels: [APP=JAR]
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 10s
      timeout: 10s
      retries: 30



  bridgeq:
    image: gennyproject/bridgeq:latest
    depends_on:
      apiq:
        condition: service_healthy
    environment:
      - ADMIN_USERNAME=GENNY
      - ADMIN_PASSWORD=GENNY
      - VIRTUAL_HOST=bridge.genny.life
      - VIRTUAL_PORT=8088
      - VIRTUAL_PROTO=http
      - CERT_NAME=genny.life
      - KEYCLOAKURL=https://keycloak.gada.io/auth/realms
      - CACHE_SERVER_NAME=qwanda-service
      - DDTHOST=TRUE
      - API_PORT=8088
      - CACHE_API_PORT=8089
      - MODE_GZIP=TRUE
      - ZIP_MIN_THRESHOLD_BYTES=8000000
      - MEDIA_PROXY_URL=https://alyson.genny.life/web/public
    networks:
      - mainproxy
    deploy:
      replicas: 2 
      labels: [APP=JAR]
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
    #ports:
      #- 8088:8088
      #- 8790:8787
      #- 8089:8089
      #- 5701:5701
      #- 10001:10001
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 10s
      timeout: 10s
      retries: 30

  alysonq:
    image: gennyproject/alyson:latest
    container_name: alysonq
    depends_on:
      - bridgeq
    ports:
      - "7000:8080"
    environment:
      - VIRTUAL_HOST=internmatch.*,mentormatch.*,capstonematch.*,stt.genny.life,alyson.*
      - VIRTUAL_PORT=8080
      - NODE_ENV=production
    networks:
      - mainproxy
    restart: always


  minioq:
    image: minio/minio:latest
    container_name: minioq
    environment:
      - MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE
      - MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    volumes:
      - minio_data:/data:delegated
      - minio_conf:/root/.minio:delegated
    networks:
      - mainproxy
    ports:
      - 9000:9000
    command: server /data



  mysqlq:
    image: gennyproject/mysql:8x 
    container_name: mysqlq
    environment:
      - MYSQL_URL=mysqlq
      - MYSQL_DB=gennydb
      - MYSQL_PORT=3306
      - MYSQL_ALLOW_EMPTY=
      - MYSQL_RANDOM_ROOT_PASSWORD=no
      - MYSQL_DATABASE=gennydb
      - MYSQL_USER=genny
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=AdamDavidMoeSame2020
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mainproxy
    ports:
      - 3310:3306
    command: --sql_mode=""  --default_authentication_plugin=mysql_native_password  --sort_buffer_size=1073741824
    deploy:
      placement:
        max_replicas_per_node: 1
        constraints:
          - "node.role==manager"
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  keycloakq:
    image: jboss/keycloak:12.0.1
    container_name: keycloakq
    environment:
        - KEYCLOAK_USER=admin
        - KEYCLOAK_PASSWORD=admin
        - DB_VENDOR=mysql
        - DB_ADDR=mysqlq
        - DB_PORT=3306
        - DB_DATABASE=gennydb
        - DB_USER=genny
        - DB_PASSWORD=password
        - PROXY_ADDRESS_FORWARDING=true
        - KEYCLOAK_LOGLEVEL=debug
        - JAVA_OPTS_APPEND="-Djava.awt.headless=true"
        - PREPEND_JAVA_OPTS=-Dkeycloak.profile=preview -Dkeycloak.profile.feature.token_exchange=enabled -Dkeycloak.profile.feature.account_api=enabled
        - KEYCLOAK_IMPORT=/config/quarkus-realm.json
    volumes:
      - ./config:/config 
    ports:
      - 8180:8080
    networks:
      - mainproxy
    depends_on:
      - mysqlq

  nginxq:
    image: jwilder/nginx-proxy:alpine
    hostname: nginx
    #depends_on:
      #bridgeq:
        #condition: service_healthy
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    networks:
      - mainproxy
    environment:
      - SKIP_HTTPS_REDIRECT=true
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:delegated
      - ./nginx/vhost.d:/etc/nginx/vhost.d:delegated
      - ./nginx/html:/usr/share/nginx/html:delegated
      - ./nginx/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
#    healthcheck:
#      test: ["CMD", "curl", "--fail", "http://nginx.host.com"]
#      interval: 1m30s
#      timeout: 10s
#      retries: 3
 

 
volumes:
  mysql_data:
  minio_conf:
  minio_data:
  maildata:
    driver: local
  mailstate:
    driver: local
networks:
  mainproxy:
    driver: bridge
